-- Mashoke Labs — MySQL/MariaDB schema (replaces the Supabase Postgres schema)
--
-- Import via phpMyAdmin into your cPanel-created database (e.g. mashqzco_academics).
-- All UUID primary keys are CHAR(36), generated by the API layer (crypto.randomUUID()) —
-- not by the database — so this schema stays portable across MySQL 5.7/8.x and MariaDB
-- without depending on version-specific DEFAULT-expression support.
--
-- All authorization that used to live in Postgres Row Level Security policies now lives
-- in api/lib/authz.js. This file is intentionally "dumb": plain structure + foreign keys.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- auth_users — replaces Supabase's auth.users for the three credentialed roles
-- (lecturers, platform admins, institution admins). Students never get a row
-- here — they keep the existing no-password pseudo-session model.
-- ============================================================================
CREATE TABLE IF NOT EXISTS auth_users (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('lecturer', 'platform_admin', 'institution_admin') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- institutions — tenant root
-- ============================================================================
CREATE TABLE IF NOT EXISTS institutions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  contact_email VARCHAR(255) NOT NULL,
  plan ENUM('trial', 'standard', 'enterprise') NOT NULL DEFAULT 'trial',
  lecturer_seat_limit INT NOT NULL DEFAULT 5,
  student_seat_limit INT NOT NULL DEFAULT 200,
  status ENUM('active', 'suspended') NOT NULL DEFAULT 'active',
  self_serve_signup TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- lecturer_profiles / platform_admins / institution_admins
-- id = auth_users.id (1:1, same shape as the old auth.users + profile-table pattern)
-- ============================================================================
CREATE TABLE IF NOT EXISTS lecturer_profiles (
  id CHAR(36) NOT NULL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  institution_id CHAR(36) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lecturer_profiles_auth FOREIGN KEY (id) REFERENCES auth_users(id) ON DELETE CASCADE,
  CONSTRAINT fk_lecturer_profiles_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_lecturer_profiles_institution ON lecturer_profiles(institution_id);

CREATE TABLE IF NOT EXISTS platform_admins (
  id CHAR(36) NOT NULL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_platform_admins_auth FOREIGN KEY (id) REFERENCES auth_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS institution_admins (
  id CHAR(36) NOT NULL PRIMARY KEY,
  institution_id CHAR(36) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_institution_admins_auth FOREIGN KEY (id) REFERENCES auth_users(id) ON DELETE CASCADE,
  CONSTRAINT fk_institution_admins_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_institution_admins_institution ON institution_admins(institution_id);

-- ============================================================================
-- students — NOT in auth_users. Pseudo-session model unchanged from Supabase:
-- the API returns the raw row, the frontend stores it in localStorage, no JWT.
-- ============================================================================
CREATE TABLE IF NOT EXISTS students (
  id CHAR(36) NOT NULL PRIMARY KEY,
  student_number VARCHAR(64) NOT NULL UNIQUE,
  full_name VARCHAR(255) DEFAULT NULL,
  institution_id CHAR(36) DEFAULT NULL,
  cohort_id CHAR(36) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  exam_id CHAR(36) DEFAULT NULL, -- legacy single-exam link, superseded by `enrollments`
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_students_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_students_institution ON students(institution_id);
CREATE INDEX idx_students_cohort ON students(cohort_id);

-- ============================================================================
-- cohorts
-- ============================================================================
CREATE TABLE IF NOT EXISTS cohorts (
  id CHAR(36) NOT NULL PRIMARY KEY,
  institution_id CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cohorts_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_cohorts_institution ON cohorts(institution_id);

ALTER TABLE students ADD CONSTRAINT fk_students_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id) ON DELETE SET NULL;

-- ============================================================================
-- subjects — per-lecturer exam folders
-- ============================================================================
CREATE TABLE IF NOT EXISTS subjects (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  lecturer_id CHAR(36) NOT NULL,
  institution_id CHAR(36) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_subjects_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_subjects_lecturer ON subjects(lecturer_id);
CREATE INDEX idx_subjects_institution ON subjects(institution_id);

-- ============================================================================
-- exams
-- ============================================================================
CREATE TABLE IF NOT EXISTS exams (
  id CHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  lecturer_id CHAR(36) NOT NULL,
  institution_id CHAR(36) DEFAULT NULL,
  duration_minutes INT NOT NULL DEFAULT 60,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  total_marks INT NOT NULL DEFAULT 100,
  default_marks_per_question INT NOT NULL DEFAULT 1,
  allowed_violations INT NOT NULL DEFAULT 3,
  allowed_attempts INT NOT NULL DEFAULT 1,
  enrollment_code VARCHAR(12) NOT NULL UNIQUE,
  exam_type ENUM('mcq_only', 'structured_only', 'mixed') NOT NULL DEFAULT 'mixed',
  subject_id CHAR(36) DEFAULT NULL,
  exam_mode ENUM('closed_book', 'open_book') NOT NULL DEFAULT 'closed_book',
  has_coding TINYINT(1) NOT NULL DEFAULT 0,
  coding_language VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exams_lecturer FOREIGN KEY (lecturer_id) REFERENCES auth_users(id) ON DELETE CASCADE,
  CONSTRAINT fk_exams_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE,
  CONSTRAINT fk_exams_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_exams_lecturer ON exams(lecturer_id);
CREATE INDEX idx_exams_institution ON exams(institution_id);
CREATE INDEX idx_exams_enrollment_code ON exams(enrollment_code);
CREATE INDEX idx_exams_active ON exams(is_active);

-- ============================================================================
-- questions
-- ============================================================================
CREATE TABLE IF NOT EXISTS questions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  exam_id CHAR(36) NOT NULL,
  type ENUM('mcq', 'structured') NOT NULL,
  question_text TEXT NOT NULL,
  options JSON DEFAULT NULL,
  correct_answer TEXT DEFAULT NULL,
  marks INT NOT NULL DEFAULT 1,
  order_index INT NOT NULL DEFAULT 0,
  can_copy TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_questions_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_questions_exam_order ON questions(exam_id, order_index);

-- ============================================================================
-- enrollments — many-to-many student<->exam
-- ============================================================================
CREATE TABLE IF NOT EXISTS enrollments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  student_id CHAR(36) NOT NULL,
  exam_id CHAR(36) NOT NULL,
  enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_enrollments_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  CONSTRAINT uq_enrollments_student_exam UNIQUE (student_id, exam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_enrollments_exam_student ON enrollments(exam_id, student_id);

-- ============================================================================
-- submissions
-- ============================================================================
CREATE TABLE IF NOT EXISTS submissions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  exam_id CHAR(36) NOT NULL,
  student_id CHAR(36) NOT NULL,
  answers JSON NOT NULL,
  score DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_marks INT NOT NULL DEFAULT 0,
  graded TINYINT(1) NOT NULL DEFAULT 0,
  marking_details JSON NOT NULL,
  is_manual TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('draft', 'submitted') NOT NULL DEFAULT 'submitted',
  marked_by_email VARCHAR(255) DEFAULT NULL,
  marked_by_name VARCHAR(255) DEFAULT NULL,
  attempt_number INT NOT NULL DEFAULT 1,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_submissions_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  CONSTRAINT fk_submissions_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT uq_submissions_exam_student_attempt UNIQUE (exam_id, student_id, attempt_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_submissions_exam_student ON submissions(exam_id, student_id);
CREATE INDEX idx_submissions_student_status ON submissions(student_id, status);

-- ============================================================================
-- deleted_submissions — trash box, populated by the API (not a DB trigger) on
-- submission delete; restore re-inserts into `submissions` and deletes here.
-- ============================================================================
CREATE TABLE IF NOT EXISTS deleted_submissions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  exam_id CHAR(36) DEFAULT NULL,
  student_id CHAR(36) DEFAULT NULL,
  answers JSON DEFAULT NULL,
  score DECIMAL(10,2) DEFAULT NULL,
  total_marks INT DEFAULT NULL,
  graded TINYINT(1) DEFAULT NULL,
  is_manual TINYINT(1) DEFAULT NULL,
  status VARCHAR(16) DEFAULT NULL,
  marking_details JSON DEFAULT NULL,
  marked_by_email VARCHAR(255) DEFAULT NULL,
  marked_by_name VARCHAR(255) DEFAULT NULL,
  submitted_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_deleted_submissions_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  CONSTRAINT fk_deleted_submissions_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- violations
-- ============================================================================
CREATE TABLE IF NOT EXISTS violations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  student_id CHAR(36) NOT NULL,
  exam_id CHAR(36) NOT NULL,
  violation_type ENUM('tab_switch', 'fullscreen_exit', 'blur', 'cursor_exit') NOT NULL,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_violations_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_violations_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_violations_exam_student ON violations(exam_id, student_id);
CREATE INDEX idx_violations_student ON violations(student_id);

-- ============================================================================
-- exam_lecturers — co-marker collaboration, matched by email (not FK) exactly
-- as before, since a co-marker may be added before they have an account
-- ============================================================================
CREATE TABLE IF NOT EXISTS exam_lecturers (
  id CHAR(36) NOT NULL PRIMARY KEY,
  exam_id CHAR(36) NOT NULL,
  lecturer_email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_exam_lecturers_exam FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  CONSTRAINT uq_exam_lecturers UNIQUE (exam_id, lecturer_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- issues — support tickets, institution-scoped, escalate to the platform queue
-- ============================================================================
CREATE TABLE IF NOT EXISTS issues (
  id CHAR(36) NOT NULL PRIMARY KEY,
  institution_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  category ENUM('technical', 'grading', 'billing', 'account') NOT NULL,
  status ENUM('open', 'in_progress', 'escalated', 'resolved') NOT NULL DEFAULT 'open',
  reporter_name VARCHAR(255) NOT NULL,
  reporter_role VARCHAR(32) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_issues_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_issues_institution ON issues(institution_id);
CREATE INDEX idx_issues_status ON issues(status);

-- ============================================================================
-- subscriptions / invoices — internal billing record-keeping, no gateway
-- ============================================================================
CREATE TABLE IF NOT EXISTS subscriptions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  institution_id CHAR(36) NOT NULL UNIQUE,
  plan ENUM('trial', 'standard', 'enterprise') NOT NULL DEFAULT 'trial',
  price_per_month DECIMAL(10,2) NOT NULL DEFAULT 0,
  cycle ENUM('monthly', 'annual', 'trial') NOT NULL DEFAULT 'trial',
  next_invoice_date DATE DEFAULT NULL,
  status ENUM('paid', 'past_due', 'trialing') NOT NULL DEFAULT 'trialing',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_subscriptions_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoices (
  id CHAR(36) NOT NULL PRIMARY KEY,
  institution_id CHAR(36) NOT NULL,
  invoice_date DATE NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status ENUM('paid', 'past_due', 'trialing') NOT NULL DEFAULT 'paid',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_invoices_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_invoices_institution ON invoices(institution_id, invoice_date);

-- ============================================================================
-- platform_settings — singleton (id is always 1, enforced in the API layer)
-- ============================================================================
CREATE TABLE IF NOT EXISTS platform_settings (
  id INT NOT NULL PRIMARY KEY,
  standard_price DECIMAL(10,2) NOT NULL DEFAULT 49.00,
  enterprise_price DECIMAL(10,2) NOT NULL DEFAULT 199.00,
  announcement TEXT NOT NULL,
  announcement_published TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO platform_settings (id, standard_price, enterprise_price, announcement, announcement_published)
VALUES (1, 49.00, 199.00, '', 0);

-- ============================================================================
-- feature_flags
-- ============================================================================
CREATE TABLE IF NOT EXISTS feature_flags (
  `key` VARCHAR(64) NOT NULL PRIMARY KEY,
  label VARCHAR(255) NOT NULL,
  detail TEXT NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO feature_flags (`key`, label, detail, enabled) VALUES
  ('ai_assisted_grading', 'AI-assisted grading', 'Gemini/OpenAI auto-marking in the grading workflow', 1),
  ('open_book_exam_mode', 'Open-book exam mode', 'Allows exams to be configured as open-book', 1),
  ('coding_sandbox', 'In-browser coding sandbox', 'Kotlin Playground coding questions', 1),
  ('institution_self_serve_signup', 'Institution self-serve signup', 'Allow institutions to sign up without a platform admin invite', 0);

-- ============================================================================
-- audit_log — append-only, written only via api/lib/auditLog.js (never a
-- direct client insert — enforced by the API, since MySQL has no RLS to do it)
-- ============================================================================
CREATE TABLE IF NOT EXISTS audit_log (
  id CHAR(36) NOT NULL PRIMARY KEY,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor_id CHAR(36) DEFAULT NULL,
  actor_name VARCHAR(255) NOT NULL,
  actor_role VARCHAR(32) NOT NULL,
  institution_id CHAR(36) DEFAULT NULL,
  action VARCHAR(255) NOT NULL,
  target VARCHAR(255) NOT NULL,
  CONSTRAINT fk_audit_log_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_audit_log_occurred_at ON audit_log(occurred_at);
CREATE INDEX idx_audit_log_institution ON audit_log(institution_id);

-- ============================================================================
-- institution_stats — derived seat-usage counts (avoids drifting counters)
-- ============================================================================
CREATE OR REPLACE VIEW institution_stats AS
SELECT
  i.id AS institution_id,
  COUNT(DISTINCT lp.id) AS lecturer_count,
  COUNT(DISTINCT s.id) AS student_count
FROM institutions i
LEFT JOIN lecturer_profiles lp ON lp.institution_id = i.id
LEFT JOIN students s ON s.institution_id = i.id
GROUP BY i.id;

SET FOREIGN_KEY_CHECKS = 1;
